-- Profiles table to track premium status
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  clerk_id TEXT UNIQUE NOT NULL,
  is_premium BOOLEAN DEFAULT FALSE,
  subscription_end_date TIMESTAMP WITH TIME ZONE
);

-- Favorites table for user engagement
CREATE TABLE favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  chapter INT NOT NULL,
  verse INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
